### PR TITLE
Updates to the code and documentation for new APL 1.3 best practices with data binding

### PR DESCRIPTION
**Pull request by JoeMoCode**
Changes to the code and the documentation based on the changes to "payload" and data binding in APL 1.3

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by HeIp** [comment]
Can someone approve this, this has been pending for the longest.
And is an important correction to the code that is mentioned in the https://developer.amazon.com/en-US/alexa/alexa-skills-kit/get-deeper/tutorials-code-samples/build-a-multimodal-alexa-skill/ tutorial. 
Otherwise it's just outdated code here confusing future alexa developers.
Causing issues mentioned #3

**Comment by JoeMoCode** [comment]
Thanks, Help! Will fix the conflicts and repost.

**Comment by HeIp** [comment]
No problem, this is a much needed change. They're using outdated legacy code that didn't match the tutorial. 
I'm glad I looked at your pull request to see what I was doing wrong & to see the tutorial was also wrong.

**Comment by JoeMoCode** [comment]
I'm glad you looked, also! Thanks for bringing this to my attention.

**Comment by HeIp** [comment]
Any time and you're welcome @JoeMoCode Issue #3 I believe can be closed now

**Pull request merged**
